list1 = [False,True,True,None,True,None,None,False,False,None,True,False]
list2 = ["or","or","or","==","!=","==","and","==","!=","and","==","or"]
list3 = [False,False,None,None,True,True,False,True,None,False,True,None]

Boolexp1 = (str(list1[0]) + " " + str(list2[0]) + " " + str(list3[0]))
print str(Boolexp1) + " ==> " + str(eval(Boolexp1))
Boolexp2 = (str(list1[1]) + " " + str(list2[1]) + " " + str(list3[1]))
print str(Boolexp2) + " ==> " + str(eval(Boolexp2))
Boolexp3 = (str(list1[2]) + " " + str(list2[2]) + " " + str(list3[2]))
print str(Boolexp3) + " ==> " + str(eval(Boolexp3))
Boolexp4 = (str(list1[3]) + " " + str(list2[3]) + " " + str(list3[3]))
print str(Boolexp4) + " ==> " + str(eval(Boolexp4))
Boolexp5 = (str(list1[4]) + " " + str(list2[4]) + " " + str(list3[4]))
print str(Boolexp5) + " ==> " + str(eval(Boolexp5))
Boolexp6 = (str(list1[5]) + " " + str(list2[5]) + " " + str(list3[5]))
print str(Boolexp6) + " ==> " + str(eval(Boolexp6))
Boolexp7 = (str(list1[6]) + " " + str(list2[6]) + " " + str(list3[6]))
print str(Boolexp7) + " ==> " + str(eval(Boolexp7))
Boolexp8 = (str(list1[7]) + " " + str(list2[7]) + " " + str(list3[7]))
print str(Boolexp8) + " ==> " + str(eval(Boolexp8))
Boolexp9 = (str(list1[8]) + " " + str(list2[8]) + " " + str(list3[8]))
print str(Boolexp9) + " ==> " + str(eval(Boolexp9))
Boolexp10 = (str(list1[9]) + " " + str(list2[9]) + " " + str(list3[9]))
print str(Boolexp10) + " ==> " + str(eval(Boolexp10))
Boolexp11 = (str(list1[10]) + " " + str(list2[10]) + " " + str(list3[10]))
print str(Boolexp11) + " ==> " + str(eval(Boolexp11))
Boolexp12 = (str(list1[11]) + " " + str(list2[11]) + " " + str(list3[11]))
print str(Boolexp12) + " ==> " + str(eval(Boolexp12))